name: Test

on:
  pull_request:
    branches: [legacy-0.1]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Node.js packages
        run: npm ci
      - name: Build
        run: npm build
